"""add dispatched column to items

Revision ID: 9e36f2809121
Revises: c234b7722ac5
Create Date: 2026-03-20 17:31:13.596552

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9e36f2809121'
down_revision: Union[str, Sequence[str], None] = 'c234b7722ac5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # 1. Add the column allowing NULLs initially
    op.add_column('items', sa.Column('dispatched', sa.Boolean(), nullable=True))
    
    # 2. Set all existing rows to 'False'
    op.execute("UPDATE items SET dispatched = False")
    
    # 3. Now change the column to NOT NULL
    op.alter_column('items', 'dispatched', nullable=False)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('items', 'dispatched')
    # ### end Alembic commands ###
